export type Lang = "ru" | "kz" | "en";

export interface ToolMeta {
  id: string;
  category: string;
  slug: string;
  nameKey: string;
  descriptionKey: string;
  similarTools?: string[];
}

export const CATEGORIES: Record<string, { key: string; tools: string[] }> = {
  text: {
    key: "nav.text",
    tools: [
      "word-counter",
      "case-converter",
      "translit",
      "reverse-text",
      "fonts-social",
      "space-cleanup",
      "zalgo",
      "lorem-ipsum",
    ],
  },
  random: {
    key: "nav.random",
    tools: [
      "random-number",
      "random-picker",
      "wheel-fortune",
      "dice",
      "password-generator",
      "uuid",
      "list-shuffler",
    ],
  },
  time: {
    key: "nav.time",
    tools: ["pomodoro", "stopwatch", "countdown", "world-time", "timers", "unix-converter"],
  },
  math: {
    key: "nav.math",
    tools: [
      "percent-calc",
      "bmi",
      "loan-calc",
      "vat-calc",
      "tip-calculator",
      "number-systems",
    ],
  },
  graphics: {
    key: "nav.graphics",
    tools: [
      "image-compress",
      "color-picker",
      "css-gradients",
      "base64",
      "qr-generator",
      "favicon-gen",
    ],
  },
  "dev-tools": {
    key: "nav.devTools",
    tools: [
      "json-formatter",
      "jwt-decoder",
      "diff-checker",
      "html-encode",
      "url-encode",
      "regex-tester",
    ],
  },
  social: {
    key: "nav.social",
    tools: [
      "utm-builder",
      "yt-tags",
      "char-limits",
      "wa-link-generator",
    ],
  },
  converters: {
    key: "nav.converters",
    tools: [
      "weight-converter",
      "length-converter",
      "volume-converter",
      "currency-converter",
      "roman-numerals",
    ],
  },
  crypto: {
    key: "nav.crypto",
    tools: ["md5", "sha256", "aes-encrypt", "morse-code"],
  },
  misc: {
    key: "nav.misc",
    tools: ["cps-test", "metronome", "notepad"],
  },
};

export const TOOLS: Record<string, ToolMeta> = {
  "word-counter": {
    id: "word-counter",
    category: "text",
    slug: "word-counter",
    nameKey: "tools.wordCounter.title",
    descriptionKey: "tools.wordCounter.description",
    similarTools: ["case-converter", "char-limits", "translit"],
  },
  "case-converter": {
    id: "case-converter",
    category: "text",
    slug: "case-converter",
    nameKey: "tools.caseConverter.title",
    descriptionKey: "tools.caseConverter.description",
    similarTools: ["word-counter", "translit", "zalgo"],
  },
  translit: {
    id: "translit",
    category: "text",
    slug: "translit",
    nameKey: "tools.translit.title",
    descriptionKey: "tools.translit.description",
    similarTools: ["case-converter", "word-counter"],
  },
  "fonts-social": {
    id: "fonts-social",
    category: "text",
    slug: "fonts-social",
    nameKey: "tools.fontsSocial.title",
    descriptionKey: "tools.fontsSocial.description",
    similarTools: ["zalgo", "case-converter"],
  },
  "space-cleanup": {
    id: "space-cleanup",
    category: "text",
    slug: "space-cleanup",
    nameKey: "tools.spaceCleanup.title",
    descriptionKey: "tools.spaceCleanup.description",
    similarTools: ["word-counter", "case-converter"],
  },
  zalgo: {
    id: "zalgo",
    category: "text",
    slug: "zalgo",
    nameKey: "tools.zalgo.title",
    descriptionKey: "tools.zalgo.description",
    similarTools: ["fonts-social", "case-converter"],
  },
  "lorem-ipsum": {
    id: "lorem-ipsum",
    category: "text",
    slug: "lorem-ipsum",
    nameKey: "tools.loremIpsum.title",
    descriptionKey: "tools.loremIpsum.description",
    similarTools: ["random-number", "password-generator"],
  },
  "reverse-text": {
    id: "reverse-text",
    category: "text",
    slug: "reverse-text",
    nameKey: "tools.reverseText.title",
    descriptionKey: "tools.reverseText.description",
    similarTools: ["case-converter", "translit", "zalgo"],
  },
  "random-number": {
    id: "random-number",
    category: "random",
    slug: "random-number",
    nameKey: "tools.randomNumber.title",
    descriptionKey: "tools.randomNumber.description",
    similarTools: ["password-generator", "uuid", "list-shuffler"],
  },
  "random-picker": {
    id: "random-picker",
    category: "random",
    slug: "random-picker",
    nameKey: "tools.randomPicker.title",
    descriptionKey: "tools.randomPicker.description",
    similarTools: ["wheel-fortune", "list-shuffler", "random-number"],
  },
  "wheel-fortune": {
    id: "wheel-fortune",
    category: "random",
    slug: "wheel-fortune",
    nameKey: "tools.wheelFortune.title",
    descriptionKey: "tools.wheelFortune.description",
    similarTools: ["dice", "random-number", "list-shuffler"],
  },
  dice: {
    id: "dice",
    category: "random",
    slug: "dice",
    nameKey: "tools.dice.title",
    descriptionKey: "tools.dice.description",
    similarTools: ["random-number", "wheel-fortune"],
  },
  "password-generator": {
    id: "password-generator",
    category: "random",
    slug: "password-generator",
    nameKey: "tools.passwordGenerator.title",
    descriptionKey: "tools.passwordGenerator.description",
    similarTools: ["random-number", "uuid", "md5"],
  },
  uuid: {
    id: "uuid",
    category: "random",
    slug: "uuid",
    nameKey: "tools.uuid.title",
    descriptionKey: "tools.uuid.description",
    similarTools: ["random-number", "password-generator"],
  },
  "list-shuffler": {
    id: "list-shuffler",
    category: "random",
    slug: "list-shuffler",
    nameKey: "tools.listShuffler.title",
    descriptionKey: "tools.listShuffler.description",
    similarTools: ["random-number", "wheel-fortune"],
  },
  pomodoro: {
    id: "pomodoro",
    category: "time",
    slug: "pomodoro",
    nameKey: "tools.pomodoro.title",
    descriptionKey: "tools.pomodoro.description",
    similarTools: ["stopwatch", "timers"],
  },
  stopwatch: {
    id: "stopwatch",
    category: "time",
    slug: "stopwatch",
    nameKey: "tools.stopwatch.title",
    descriptionKey: "tools.stopwatch.description",
    similarTools: ["pomodoro", "timers", "metronome"],
  },
  countdown: {
    id: "countdown",
    category: "time",
    slug: "countdown",
    nameKey: "tools.countdown.title",
    descriptionKey: "tools.countdown.description",
    similarTools: ["timers", "pomodoro", "stopwatch"],
  },
  "world-time": {
    id: "world-time",
    category: "time",
    slug: "world-time",
    nameKey: "tools.worldTime.title",
    descriptionKey: "tools.worldTime.description",
    similarTools: ["unix-converter", "timers"],
  },
  timers: {
    id: "timers",
    category: "time",
    slug: "timers",
    nameKey: "tools.timers.title",
    descriptionKey: "tools.timers.description",
    similarTools: ["pomodoro", "stopwatch"],
  },
  "unix-converter": {
    id: "unix-converter",
    category: "time",
    slug: "unix-converter",
    nameKey: "tools.unixConverter.title",
    descriptionKey: "tools.unixConverter.description",
    similarTools: ["world-time"],
  },
  "percent-calc": {
    id: "percent-calc",
    category: "math",
    slug: "percent-calc",
    nameKey: "tools.percentCalc.title",
    descriptionKey: "tools.percentCalc.description",
    similarTools: ["vat-calc", "bmi", "loan-calc", "number-systems"],
  },
  bmi: {
    id: "bmi",
    category: "math",
    slug: "bmi",
    nameKey: "tools.bmi.title",
    descriptionKey: "tools.bmi.description",
    similarTools: ["percent-calc", "loan-calc", "vat-calc", "weight-converter"],
  },
  "loan-calc": {
    id: "loan-calc",
    category: "math",
    slug: "loan-calc",
    nameKey: "tools.loanCalc.title",
    descriptionKey: "tools.loanCalc.description",
    similarTools: ["percent-calc", "vat-calc", "bmi", "currency-converter"],
  },
  "vat-calc": {
    id: "vat-calc",
    category: "math",
    slug: "vat-calc",
    nameKey: "tools.vatCalc.title",
    descriptionKey: "tools.vatCalc.description",
    similarTools: ["percent-calc", "loan-calc", "bmi", "currency-converter"],
  },
  "tip-calculator": {
    id: "tip-calculator",
    category: "math",
    slug: "tip-calculator",
    nameKey: "tools.tipCalculator.title",
    descriptionKey: "tools.tipCalculator.description",
    similarTools: ["percent-calc", "vat-calc", "loan-calc"],
  },
  "number-systems": {
    id: "number-systems",
    category: "math",
    slug: "number-systems",
    nameKey: "tools.numberSystems.title",
    descriptionKey: "tools.numberSystems.description",
    similarTools: ["roman-numerals", "percent-calc", "base64", "url-encode"],
  },
  "image-compress": {
    id: "image-compress",
    category: "graphics",
    slug: "image-compress",
    nameKey: "tools.imageCompress.title",
    descriptionKey: "tools.imageCompress.description",
    similarTools: ["base64", "favicon-gen"],
  },
  "color-picker": {
    id: "color-picker",
    category: "graphics",
    slug: "color-picker",
    nameKey: "tools.colorPicker.title",
    descriptionKey: "tools.colorPicker.description",
    similarTools: ["css-gradients", "base64"],
  },
  "css-gradients": {
    id: "css-gradients",
    category: "graphics",
    slug: "css-gradients",
    nameKey: "tools.cssGradients.title",
    descriptionKey: "tools.cssGradients.description",
    similarTools: ["color-picker", "base64"],
  },
  base64: {
    id: "base64",
    category: "graphics",
    slug: "base64",
    nameKey: "tools.base64.title",
    descriptionKey: "tools.base64.description",
    similarTools: ["image-compress", "url-encode"],
  },
  "qr-generator": {
    id: "qr-generator",
    category: "graphics",
    slug: "qr-generator",
    nameKey: "tools.qrGenerator.title",
    descriptionKey: "tools.qrGenerator.description",
    similarTools: ["base64", "favicon-gen", "url-encode"],
  },
  "favicon-gen": {
    id: "favicon-gen",
    category: "graphics",
    slug: "favicon-gen",
    nameKey: "tools.faviconGen.title",
    descriptionKey: "tools.faviconGen.description",
    similarTools: ["image-compress", "base64"],
  },
  "json-formatter": {
    id: "json-formatter",
    category: "dev-tools",
    slug: "json-formatter",
    nameKey: "tools.jsonFormatter.title",
    descriptionKey: "tools.jsonFormatter.description",
    similarTools: ["jwt-decoder", "url-encode"],
  },
  "jwt-decoder": {
    id: "jwt-decoder",
    category: "dev-tools",
    slug: "jwt-decoder",
    nameKey: "tools.jwtDecoder.title",
    descriptionKey: "tools.jwtDecoder.description",
    similarTools: ["json-formatter", "base64"],
  },
  "diff-checker": {
    id: "diff-checker",
    category: "dev-tools",
    slug: "diff-checker",
    nameKey: "tools.diffChecker.title",
    descriptionKey: "tools.diffChecker.description",
    similarTools: ["json-formatter", "regex-tester", "word-counter"],
  },
  "html-encode": {
    id: "html-encode",
    category: "dev-tools",
    slug: "html-encode",
    nameKey: "tools.htmlEncode.title",
    descriptionKey: "tools.htmlEncode.description",
    similarTools: ["url-encode", "base64"],
  },
  "url-encode": {
    id: "url-encode",
    category: "dev-tools",
    slug: "url-encode",
    nameKey: "tools.urlEncode.title",
    descriptionKey: "tools.urlEncode.description",
    similarTools: ["html-encode", "base64", "regex-tester"],
  },
  "regex-tester": {
    id: "regex-tester",
    category: "dev-tools",
    slug: "regex-tester",
    nameKey: "tools.regexTester.title",
    descriptionKey: "tools.regexTester.description",
    similarTools: ["json-formatter", "url-encode"],
  },
  "utm-builder": {
    id: "utm-builder",
    category: "social",
    slug: "utm-builder",
    nameKey: "tools.utmBuilder.title",
    descriptionKey: "tools.utmBuilder.description",
    similarTools: ["wa-link-generator", "url-encode"],
  },
  "yt-tags": {
    id: "yt-tags",
    category: "social",
    slug: "yt-tags",
    nameKey: "tools.ytTags.title",
    descriptionKey: "tools.ytTags.description",
    similarTools: ["char-limits", "utm-builder"],
  },
  "char-limits": {
    id: "char-limits",
    category: "social",
    slug: "char-limits",
    nameKey: "tools.charLimits.title",
    descriptionKey: "tools.charLimits.description",
    similarTools: ["word-counter", "yt-tags"],
  },
  "wa-link-generator": {
    id: "wa-link-generator",
    category: "social",
    slug: "wa-link-generator",
    nameKey: "tools.waLinkGenerator.title",
    descriptionKey: "tools.waLinkGenerator.description",
    similarTools: ["utm-builder", "url-encode"],
  },
  "weight-converter": {
    id: "weight-converter",
    category: "converters",
    slug: "weight-converter",
    nameKey: "tools.weightConverter.title",
    descriptionKey: "tools.weightConverter.description",
    similarTools: ["length-converter", "currency-converter"],
  },
  "length-converter": {
    id: "length-converter",
    category: "converters",
    slug: "length-converter",
    nameKey: "tools.lengthConverter.title",
    descriptionKey: "tools.lengthConverter.description",
    similarTools: ["weight-converter", "roman-numerals"],
  },
  "volume-converter": {
    id: "volume-converter",
    category: "converters",
    slug: "volume-converter",
    nameKey: "tools.volumeConverter.title",
    descriptionKey: "tools.volumeConverter.description",
    similarTools: ["weight-converter", "length-converter"],
  },
  "currency-converter": {
    id: "currency-converter",
    category: "converters",
    slug: "currency-converter",
    nameKey: "tools.currencyConverter.title",
    descriptionKey: "tools.currencyConverter.description",
    similarTools: ["weight-converter", "vat-calc"],
  },
  "roman-numerals": {
    id: "roman-numerals",
    category: "converters",
    slug: "roman-numerals",
    nameKey: "tools.romanNumerals.title",
    descriptionKey: "tools.romanNumerals.description",
    similarTools: ["number-systems", "length-converter"],
  },
  md5: {
    id: "md5",
    category: "crypto",
    slug: "md5",
    nameKey: "tools.md5.title",
    descriptionKey: "tools.md5.description",
    similarTools: ["sha256", "aes-encrypt", "morse-code"],
  },
  sha256: {
    id: "sha256",
    category: "crypto",
    slug: "sha256",
    nameKey: "tools.sha256.title",
    descriptionKey: "tools.sha256.description",
    similarTools: ["md5", "aes-encrypt"],
  },
  "aes-encrypt": {
    id: "aes-encrypt",
    category: "crypto",
    slug: "aes-encrypt",
    nameKey: "tools.aesEncrypt.title",
    descriptionKey: "tools.aesEncrypt.description",
    similarTools: ["md5", "sha256", "base64"],
  },
  "morse-code": {
    id: "morse-code",
    category: "crypto",
    slug: "morse-code",
    nameKey: "tools.morseCode.title",
    descriptionKey: "tools.morseCode.description",
    similarTools: ["base64", "translit"],
  },
  "cps-test": {
    id: "cps-test",
    category: "misc",
    slug: "cps-test",
    nameKey: "tools.cpsTest.title",
    descriptionKey: "tools.cpsTest.description",
    similarTools: ["metronome", "stopwatch"],
  },
  metronome: {
    id: "metronome",
    category: "misc",
    slug: "metronome",
    nameKey: "tools.metronome.title",
    descriptionKey: "tools.metronome.description",
    similarTools: ["stopwatch", "timers", "cps-test"],
  },
  notepad: {
    id: "notepad",
    category: "misc",
    slug: "notepad",
    nameKey: "tools.notepad.title",
    descriptionKey: "tools.notepad.description",
    similarTools: ["word-counter", "case-converter"],
  },
};
